/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackgroundAnimation: typeof import('./src/components/BackgroundAnimation.vue')['default']
    CvCard: typeof import('./src/components/CvCard.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SingleSelect: typeof import('./src/components/SingleSelect.vue')['default']
    ToggleSwitch: typeof import('./src/components/ToggleSwitch.vue')['default']
  }
}
